Added command to unlock annex repo to restore files from symbolic links.
NeuralEnsemble/python-neo pull request #1559
Opened 2024-09-18 16:14 UTC by nikhilchandra

fixes #1550 

I did a little digging and I think the problems with downloaded files being replaced with 1KB symbolic links has to do with the way annex repositories work. I added an "unlock" command after the forced checkout and it seems to fix the issue on my Windows computer.

2024-09-18 16:51 UTC, zm711 commented
It looks to me like this doesn't break the linux based CI. I'll leave this open for a little bit to see if anyone else has feelings about this, but I'm okay with it.

2024-09-18 18:01 UTC, nikhilchandra commented
@zm711 I have not been very active on github until recently. I used Bitbucket in grad school and since my projects were solo everything was in private repos.

If you don't mind, I would prefer to not merge this pull request. It worked yesterday on my machine for test_plexon2rawio.py but I just ran pytest again from the root directory and there are a lot of breaks. I would like to hold off until there is a better understanding of what's going on.

2024-09-18 18:04 UTC, zm711 commented
Yeah, I'll mark as `request changes` which lets the team know not to merge.

I was mainly asking to make sure you got credit for your contributions unless you had some setting for privacy. This seems like a github bug in that it is is saying that you haven't contributed anything to the repo. Seems weird, but who knows.

2024-09-18 18:04 UTC, zm711 requested changes
We need more local testing. Do not merge.

2024-09-18 18:08 UTC, zm711 commented
Not that I know of. You can use my throw away email if needed mineurs-torrent0x [at] icloud.com

2024-10-11 13:27 UTC, zm711 commented
@JuliaSprenger could you comment on this please?

2024-10-12 16:15 UTC, zm711 commented
Hey @nikhilchandra we've discussed this a bit more and we agree with the git-annex and datalad documentation that basically we don't know if this will ever really work with Windows so the preferred for this testing is to use Mac/Linux. You could try to mimic what @h-mayorquin has done in the spikeinterface ci to get windows to work for some stuff. We can wait to see if @JuliaSprenger has any opinions on this, but we will likely close this if she doesn't feel strongly about this.

2026-07-07 16:32 UTC, closed without merging